#!/bin/bash

NAME_T="$(cat $1 | grep 'Source: ' | cut -d ':' -f2)"
NAME="$(echo -e "${NAME_T}" | tr -d '[:space:]')"

cd $2

mkdir -p /results/$NAME

# A more random approach, we can't build project depending on cmake and more.
debian/rules clean
debian/rules build
if [ -f Makefile ]; then
  make clean
  START_TIME=$(date +%s.%N)
  make
  ELAPSED_TIME=$(echo "$(date +%s.%N) - $START_TIME" | bc)
  printf "%.2f\n" $ELAPSED_TIME > /results/$NAME/$NAME.time
  make -pn > /results/$NAME/$NAME.makedb
else
  rm -rf /results/$NAME/*
  echo "Couln't find Makefile" > /results/$NAME/$NAME.warning
fi

