#!/bin/bash

NAME_T="$(cat $1 | grep 'Source: ' | cut -d ':' -f2)"
NAME="$(echo -e "${NAME_T}" | tr -d '[:space:]')"

cd $2

echo "$(pwd)" > /straces/$NAME/$NAME.path

# A more random approach, we can't build project depending on cmake and more.
debian/rules clean 2> /straces/$NAME/$NAME.conferr
MAKE="fsmake-make" strace -s 4096 -f -e "$(tr -s '\r\n' ',' < /root/syscalls.txt | \
sed -e 's/,$/\n/')" -o /straces/$NAME/$NAME.straces debian/rules build 2> /straces/$NAME/$NAME.strerr > /straces/$NAME/$NAME.makedb
