#!/bin/bash

NAME_T="$(cat $1 | grep 'Source: ' | cut -d ':' -f2)"
NAME="$(echo -e "${NAME_T}" | tr -d '[:space:]')"

cd $2

mkdir -p /results/$NAME

echo "$(pwd)" > /results/$NAME/$NAME.path

# A more random approach, we can't build project depending on cmake and more.
debian/rules clean 2> /results/$NAME/$NAME.conferr
debian/rules build
if [ -f Makefile ]; then
  for i in {1..5}; do
  make clean
  fsmove make-tool -print-stats -build-dir "$(pwd)" \
    -mode online >> /results/$NAME/$NAME.faults 2> /results/$NAME/$NAME.fserr
  done
  make -pn > /results/$NAME/$NAME.makedb
else
  rm -rf /results/$NAME/*
  echo "Couln't find Makefile" > /results/$NAME/$NAME.warning
fi

