@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD bar produced !open
newFd AT_FDCWD bar @NUM@ !open
done
Operation sync_13 do
delFd @NUM@ !close
done
Operation async_4 do
hpath AT_FDCWD bar consumed !open
newFd AT_FDCWD bar @NUM@ !open
hpath AT_FDCWD foo produced !open
newFd AT_FDCWD foo @NUM@ !open
delFd @NUM@ !close
delFd @NUM@ !close
done
Operation async_5 do
hpath AT_FDCWD baz consumed !open
newFd AT_FDCWD baz !open !failed
done
Operation async_6 do
hpath AT_FDCWD bar consumed !open
newFd AT_FDCWD bar @NUM@ !open
hpath AT_FDCWD foo produced !open
newFd AT_FDCWD foo @NUM@ !open
delFd @NUM@ !close
delFd @NUM@ !close
done
Begin MAIN 1
@PROLOGUE_BLOCK@
submitOp sync_12 SYNC !node_open
submitOp sync_13 SYNC !node_close
newEvent 4 EXTERNAL !fs !node_copyFile
link 1 4
submitOp async_4 4 ASYNC !node_copyFile
newEvent 5 EXTERNAL !fs !node_copyFile
link 1 5
submitOp async_5 5 ASYNC !node_copyFile
End
Begin 4
End
Begin 5
newEvent 6 EXTERNAL !fs !node_copyFile
link 5 6
submitOp async_6 6 ASYNC !node_copyFile
End
Begin 6
End
@IGNORE@
5,6,creates
MAIN_1,4,creates
MAIN_1,5,creates
@IGNORE@
@CURRENT_DIR@/bar,4,consumed
@CURRENT_DIR@/bar,6,consumed
@CURRENT_DIR@/bar,MAIN_1,produced
@CURRENT_DIR@/baz,5,consumed
@CURRENT_DIR@/compound.js,MAIN_1,consumed
@CURRENT_DIR@/foo,4,produced
@CURRENT_DIR@/foo,6,produced
@IGNORE@
Detected Data Races
-------------------
Number of data races: 1
* Event: 4 (tags: !fs !node_copyFile) and Event: 6 (tags: !fs !node_copyFile):
  - Path @CURRENT_DIR@/foo:
    produced by the first event (operation: open)
    produced by the second event (operation: open)
