@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD bar produced
newFd AT_FDCWD bar @NUM@
done
Operation sync_13 do
delFd @NUM@
done
Operation async_4 do
hpath AT_FDCWD bar consumed
newFd AT_FDCWD bar @NUM@
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
delFd @NUM@
delFd @NUM@
done
Operation async_5 do
hpath AT_FDCWD baz consumed
newFd AT_FDCWD baz -1 !failed
done
Operation async_6 do
hpath AT_FDCWD bar consumed
newFd AT_FDCWD bar @NUM@
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
delFd @NUM@
delFd @NUM@
done
Begin MAIN
@PROLOGUE_BLOCK@
submitOp sync_12 SYNC !open
submitOp sync_13 SYNC !close
newEvent 4 EXTERNAL !fs !copyFile
link 1 4
submitOp async_4 4 ASYNC !copyFile
newEvent 5 EXTERNAL !fs !copyFile
link 1 5
submitOp async_5 5 ASYNC !copyFile
End
Begin 4
End
Begin 5
newEvent 6 EXTERNAL !fs !copyFile
link 5 6
submitOp async_6 6 ASYNC !copyFile
End
Begin 6
End
@IGNORE@
1,4,creates
1,5,creates
5,6,creates
@IGNORE@
@CURRENT_DIR@/bar,1,produced
@CURRENT_DIR@/bar,4,consumed
@CURRENT_DIR@/bar,6,consumed
@CURRENT_DIR@/baz,5,consumed
@CURRENT_DIR@/compound.js,1,consumed
@CURRENT_DIR@/foo,4,produced
@CURRENT_DIR@/foo,6,produced
