@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_23 do
hpath AT_FDCWD foo produced !open
newFd AT_FDCWD foo @NUM@ !open
done
Operation async_31 do
delFd @NUM@ !close
done
Operation sync_12 do
hpath AT_FDCWD foo expunged !unlink
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 EXTERNAL
link 1 4
newEvent 5 EXTERNAL
link 1 5
newEvent 6 EXTERNAL
link 4 6
newEvent 7 S 0 !nextTick
End
Begin 7
newEvent 8 EXTERNAL
link 7 8
newEvent 9 S 0 !nextTick
End
Begin 9
End
Begin 6
newEvent 10 EXTERNAL
link 4 10
End
Begin 10
End
Begin 4
trigger 8
newEvent 11 EXTERNAL
link 8 11
newEvent 12 EXTERNAL
link 11 12
newEvent 13 S 0 !nextTick
trigger 8
trigger 8
newEvent 14 S 0 !nextTick
newEvent 15 S 0 !nextTick
End
Begin 13
newEvent 16 EXTERNAL
link 13 16
newEvent 17 S 0 !nextTick
End
Begin 14
End
Begin 15
End
Begin 17
End
Begin 4
newEvent 18 S 0 !nextTick
newEvent 19 S 0 !nextTick
End
Begin 18
newEvent 20 S 0 !nextTick
newEvent 21 S 0 !nextTick
End
Begin 19
End
Begin 20
End
Begin 21
End
Begin 12
newEvent 22 EXTERNAL
link 11 22
End
Begin 4
End
Begin 22
End
Begin 11
trigger 16
newEvent 23 EXTERNAL !fs !node_open
link 16 23
submitOp async_23 23 ASYNC !node_open
trigger 16
trigger 16
newEvent 24 S 0 !nextTick
newEvent 25 S 0 !nextTick
End
Begin 24
End
Begin 25
End
Begin 11
newEvent 26 S 0 !nextTick
newEvent 27 S 0 !nextTick
End
Begin 26
newEvent 28 S 0 !nextTick
newEvent 29 S 0 !nextTick
End
Begin 27
End
Begin 28
End
Begin 29
End
Begin 23
newEvent 30 EXTERNAL
link 23 30
End
Begin 11
End
Begin 30
newEvent 31 EXTERNAL !fs !node_close
link 30 31
submitOp async_31 31 ASYNC !node_close
End
Begin 31
submitOp sync_12 SYNC !node_unlink
End
@IGNORE@
1,4,creates
1,6,creates
1,7,creates
4,6,before
4,10,before
4,11,creates
4,12,creates
4,13,creates
4,14,creates
4,15,creates
4,18,creates
4,19,creates
6,10,creates
7,9,creates
9,4,before
11,12,before
11,22,before
11,23,creates
11,24,creates
11,25,creates
11,26,creates
11,27,creates
12,22,creates
12,23,before
13,14,before
13,17,creates
14,15,before
15,17,before
17,18,before
18,19,before
18,20,creates
18,21,creates
19,20,before
20,21,before
21,11,before
23,30,creates
23,31,before
24,25,before
25,26,before
26,27,before
26,28,creates
26,29,creates
27,28,before
28,29,before
29,23,before
30,31,creates
@IGNORE@
@CURRENT_DIR@/foo,23,produced
@CURRENT_DIR@/foo,31,expunged
@CURRENT_DIR@/http.js,1,consumed
@IGNORE@
