@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD foo produced !open
newFd AT_FDCWD foo @NUM@ !open
done
Operation sync_13 do
delFd @NUM@ !close
done
Operation sync_14 do
hpath AT_FDCWD foo expunged !unlink
done
Begin MAIN 1
@PROLOGUE_BLOCK@
newEvent 4 W 3 !setImmediate
newEvent 5 S 0 !nextTick
End
Begin 5
submitOp sync_12 SYNC !node_open
submitOp sync_13 SYNC !node_close
End
Begin 4
newEvent 6 W 1 !setTimeout
newEvent 7 W 0 !timerWrap
End
Begin 7
trigger 6
submitOp sync_14 SYNC !node_unlink
End
@IGNORE@
4,7,creates
5,4,before
MAIN_1,4,creates
MAIN_1,5,creates
@IGNORE@
@CURRENT_DIR@/foo,5,produced
@CURRENT_DIR@/foo,7,expunged
@CURRENT_DIR@/immediate-timeout-tick.js,MAIN_1,consumed
@IGNORE@
