Starting the FSRacer Client...
Done
NodeTrace: PID [0-9]+, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation async_4 do
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo 19
done
Operation async_6 do
delFd 19
done
Operation async_7 do
hpath AT_FDCWD foo consumed
newFd AT_FDCWD foo 19
done
Operation async_10 do
delFd 19
done
Operation async_11 do
hpath AT_FDCWD foo expunged
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 EXTERNAL
Link 1 4
SubmitOp async_4 open ASYNC
End
Begin 4
newEvent 5 EXTERNAL
Link 4 5
End
Begin 5
newEvent 6 EXTERNAL
Link 5 6
SubmitOp async_6 close ASYNC
End
Begin 6
newEvent 7 EXTERNAL
Link 6 7
SubmitOp async_7 open ASYNC
End
Begin 7
newEvent 8 EXTERNAL
Link 7 8
End
Begin 8
newEvent 9 EXTERNAL
Link 8 9
End
Begin 9
newEvent 10 EXTERNAL
Link 9 10
SubmitOp async_10 close ASYNC
End
Begin 10
newEvent 11 EXTERNAL
Link 10 11
SubmitOp async_11 unlink ASYNC
End
Begin 11
End
DumpAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping dependency graph...
1,2
1,3
1,4
4,5
5,6
6,7
7,8
8,9
9,10
10,11
