@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
done
Operation sync_13 do
delFd @NUM@
done
Operation async_5 do
hpath AT_FDCWD foo expunged
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 S 0
submitOp sync_12 open SYNC
submitOp sync_13 close SYNC
End
Begin 4
newEvent 5 EXTERNAL
link 4 5
submitOp async_5 unlink ASYNC
End
Begin 5
End
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping analysis output to STDOUT
1,4,creates
4,5,creates
