Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
done
Operation sync_13 do
delFd @NUM@
done
Operation async_5 do
hpath AT_FDCWD foo expunged
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 S 0
SubmitOp sync_12 open SYNC
SubmitOp sync_13 close SYNC
End
Begin 4
newEvent 5 EXTERNAL
Link 4 5
SubmitOp async_5 unlink ASYNC
End
Begin 5
End
DumpAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping dependency graph...
1,2
1,3
1,4
4,2
4,3
4,5
