@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_14 do
hpath AT_FDCWD foo consumed
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 S 0
End
Begin 4
newEvent 8 S 0
End
Begin 8
newEvent 9 S 0
End
Begin 9
newEvent 10 S 0
End
Begin 10
newEvent 5 S 0
newEvent 11 S 0
End
Begin 5
newEvent 12 S 0
End
Begin 12
newEvent 6 S 0
newEvent 13 S 0
End
Begin 6
newEvent 14 EXTERNAL
link 7 14
submitOp async_14 access ASYNC
newEvent 7 S 0
End
Begin 14
End
@IGNORE@
1,4,creates
4,8,creates
5,12,creates
6,14,creates
8,9,creates
9,10,creates
10,5,creates
12,6,creates
@IGNORE@
@CURRENT_DIR@/foo,14,consumed
@CURRENT_DIR@/promise-chain.js,1,consumed
