@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_9 do
hpath AT_FDCWD foo produced !open
newFd AT_FDCWD foo @NUM@ !open
done
Operation async_10 do
hpath AT_FDCWD foo consumed !access
done
Operation async_11 do
hpath AT_FDCWD foo consumed !open
newFd AT_FDCWD foo @NUM@ !open
done
Operation async_14 do
delFd @NUM@ !close
done
Operation async_16 do
hpath AT_FDCWD foo expunged !unlink
done
Operation async_17 do
delFd @NUM@ !close
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 S 0 !promise
newEvent 7 S 0 !promise
End
Begin 4
newEvent 9 EXTERNAL !fs !node_open
link 5 9
submitOp async_9 9 ASYNC !node_open
newEvent 5 S 0 !promise
End
Begin 7
newEvent 10 EXTERNAL !fs !node_access
link 8 10
submitOp async_10 10 ASYNC !node_access
newEvent 8 S 0 !promise
End
Begin 5
newEvent 11 EXTERNAL !fs !node_open
link 6 11
submitOp async_11 11 ASYNC !node_open
newEvent 6 S 0 !promise
End
Begin 9
newEvent 12 EXTERNAL
link 9 12
End
Begin 10
End
Begin 11
newEvent 13 EXTERNAL
link 11 13
End
Begin 12
newEvent 14 EXTERNAL !fs !node_close
link 12 14
submitOp async_14 14 ASYNC !node_close
End
Begin 13
newEvent 15 EXTERNAL
link 13 15
End
Begin 14
newEvent 16 EXTERNAL !fs !node_unlink
link 14 16
submitOp async_16 16 ASYNC !node_unlink
End
Begin 15
newEvent 17 EXTERNAL !fs !node_close
link 15 17
submitOp async_17 17 ASYNC !node_close
End
Begin 16
End
Begin 17
End
@IGNORE@
1,4,creates
1,7,creates
4,5,creates
4,7,before
4,9,creates
5,9,before
5,10,before
5,11,creates
7,5,before
7,10,creates
9,12,creates
11,13,creates
12,14,creates
13,15,creates
14,16,creates
15,17,creates
@IGNORE@
@CURRENT_DIR@/foo,9,produced
@CURRENT_DIR@/foo,10,consumed
@CURRENT_DIR@/foo,11,consumed
@CURRENT_DIR@/foo,16,expunged
@CURRENT_DIR@/promises.js,1,consumed
