Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation async_9 do
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
done
Operation async_10 do
hpath AT_FDCWD foo consumed
done
Operation async_11 do
hpath AT_FDCWD foo consumed
newFd AT_FDCWD foo @NUM@
done
Operation async_14 do
delFd @NUM@
done
Operation async_16 do
hpath AT_FDCWD foo expunged
done
Operation async_17 do
delFd @NUM@
done
Begin 1
@PROLOGUE_BLOCK@
newEvent 4 S 0
newEvent 7 S 0
End
Begin 4
newEvent 9 W 2
Link 5 9
SubmitOp async_9 open ASYNC
newEvent 5 S 0
End
Begin 7
newEvent 10 W 2
Link 8 10
SubmitOp async_10 access ASYNC
newEvent 8 S 0
End
Begin 5
newEvent 11 W 2
Link 6 11
SubmitOp async_11 open ASYNC
newEvent 6 S 0
End
Begin 9
newEvent 12 W 2
Link 9 12
End
Begin 10
End
Begin 11
newEvent 13 W 2
Link 11 13
End
Begin 12
newEvent 14 W 2
Link 12 14
SubmitOp async_14 close ASYNC
End
Begin 13
newEvent 15 W 2
Link 13 15
End
Begin 14
newEvent 16 W 2
Link 14 16
SubmitOp async_16 unlink ASYNC
End
Begin 15
newEvent 17 W 2
Link 15 17
SubmitOp async_17 close ASYNC
End
Begin 16
End
Begin 17
End
DumpAnalyzer: Analysis is done
