@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_8 do
hpath AT_FDCWD foo consumed
done
Operation async_9 do
hpath AT_FDCWD bar consumed
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 6 S 0 !promise
newEvent 4 S 0 !promise
End
Begin 6
newEvent 8 EXTERNAL !fs !access
link 7 8
submitOp async_8 8 ASYNC !access
newEvent 7 S 0 !promise
End
Begin 4
newEvent 9 EXTERNAL !fs !access
link 5 9
submitOp async_9 9 ASYNC !access
newEvent 5 S 0 !promise
End
Begin 8
End
Begin 9
End
@IGNORE@
1,4,creates
1,6,creates
4,8,before
4,9,creates
6,4,before
6,8,creates
@IGNORE@
@CURRENT_DIR@/bar,9,consumed
@CURRENT_DIR@/foo,8,consumed
@CURRENT_DIR@/promise-thenable.js,1,consumed
