Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation async_14 do
hpath AT_FDCWD foo consumed
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 S 0
End
Begin 4
newEvent 8 S 0
End
Begin 8
newEvent 9 S 0
End
Begin 9
newEvent 10 S 0
End
Begin 10
newEvent 5 S 0
newEvent 11 S 0
End
Begin 5
newEvent 12 S 0
End
Begin 12
newEvent 6 S 0
newEvent 13 S 0
End
Begin 6
newEvent 14 EXTERNAL
Link 7 14
SubmitOp async_14 access ASYNC
newEvent 7 S 0
End
Begin 14
End
DumpAnalyzer: Analysis is done
