Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation async_14 do
hpath AT_FDCWD foo consumed
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 S 0
End
Begin 4
newEvent 8 S 0
End
Begin 8
newEvent 9 S 0
End
Begin 9
newEvent 10 S 0
End
Begin 10
newEvent 5 S 0
newEvent 11 S 0
End
Begin 5
newEvent 12 S 0
End
Begin 12
newEvent 6 S 0
newEvent 13 S 0
End
Begin 6
newEvent 14 EXTERNAL
Link 7 14
SubmitOp async_14 access ASYNC
newEvent 7 S 0
End
Begin 14
End
DumpAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping dependency graph...
1,2
1,3
1,4
4,2
4,3
4,8
5,2
5,3
5,11
5,12
6,2
6,3
6,7
6,13
6,14
7,2
7,3
7,14
8,2
8,3
8,9
9,2
9,3
9,10
10,2
10,3
10,5
10,11
11,2
11,3
11,6
11,7
11,12
11,13
11,14
12,2
12,3
12,6
12,13
13,2
13,3
13,7
13,14
