Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
done
Operation sync_13 do
delFd @NUM@
done
Operation async_5 do
hpath AT_FDCWD foo consumed
newFd AT_FDCWD foo @NUM@
done
Operation async_9 do
delFd @NUM@
done
Operation async_10 do
hpath AT_FDCWD foo expunged
done
Begin MAIN
@PROLOGUE_BLOCK@
SubmitOp sync_12 open SYNC
SubmitOp sync_13 close SYNC
newEvent 5 W 2
Link 1 5
SubmitOp async_5 open ASYNC
End
Begin 5
newEvent 7 W 2
Link 5 7
End
Begin 7
newEvent 8 W 2
Link 7 8
End
Begin 8
newEvent 9 W 2
Link 8 9
SubmitOp async_9 close ASYNC
End
Begin 9
newEvent 4 S 0
End
Begin 4
newEvent 10 W 2
Link 6 10
SubmitOp async_10 unlink ASYNC
newEvent 6 S 0
End
Begin 10
End
DumpAnalyzer: Analysis is done
