@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_8 do
hpath AT_FDCWD foo consumed !access
done
Operation async_9 do
hpath AT_FDCWD bar consumed !access
done
Begin MAIN 1
@PROLOGUE_BLOCK@
newEvent 6 S 0 !promise
newEvent 4 S 0 !promise
End
Begin 6
newEvent 8 EXTERNAL !fs !node_access
link 7 8
submitOp async_8 8 ASYNC !node_access
newEvent 7 S 0 !promise
End
Begin 4
newEvent 9 EXTERNAL !fs !node_access
link 5 9
submitOp async_9 9 ASYNC !node_access
newEvent 5 S 0 !promise
End
Begin 8
End
Begin 9
End
@IGNORE@
4,8,before
4,9,creates
6,4,before
6,8,creates
MAIN_1,4,creates
MAIN_1,6,creates
@IGNORE@
@CURRENT_DIR@/bar,9,consumed
@CURRENT_DIR@/foo,8,consumed
@CURRENT_DIR@/promise-thenable.js,MAIN_1,consumed
@IGNORE@
