Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation async_8 do
hpath AT_FDCWD foo consumed
done
Operation async_9 do
hpath AT_FDCWD bar consumed
done
Begin 1
@PROLOGUE_BLOCK@
newEvent 6 S 0
newEvent 4 S 0
End
Begin 6
newEvent 8 W 2
Link 7 8
SubmitOp async_8 access ASYNC
newEvent 7 S 0
End
Begin 4
newEvent 9 W 2
Link 5 9
SubmitOp async_9 access ASYNC
newEvent 5 S 0
End
Begin 8
End
Begin 9
End
DumpAnalyzer: Analysis is done
