@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
done
Operation sync_13 do
delFd @NUM@
done
Operation async_5 do
hpath AT_FDCWD foo consumed
newFd AT_FDCWD foo @NUM@
done
Operation async_9 do
delFd @NUM@
done
Operation async_10 do
hpath AT_FDCWD foo expunged
done
Begin MAIN
@PROLOGUE_BLOCK@
submitOp sync_12 open SYNC
submitOp sync_13 close SYNC
newEvent 5 EXTERNAL
link 1 5
submitOp async_5 open ASYNC
End
Begin 5
newEvent 7 EXTERNAL
link 5 7
End
Begin 7
newEvent 8 EXTERNAL
link 7 8
End
Begin 8
newEvent 9 EXTERNAL
link 8 9
submitOp async_9 close ASYNC
End
Begin 9
newEvent 4 S 0
End
Begin 4
newEvent 10 EXTERNAL
link 6 10
submitOp async_10 unlink ASYNC
newEvent 6 S 0
End
Begin 10
End
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping analysis output to STDOUT
1,5,creates
4,10,creates
5,7,creates
7,8,creates
8,9,creates
9,4,creates
