@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD foo produced
newFd AT_FDCWD foo @NUM@
done
Operation sync_13 do
delFd @NUM@
done
Operation async_4 do
hpath AT_FDCWD foo consumed
newFd AT_FDCWD foo @NUM@
done
Operation async_5 do
hpath AT_FDCWD bar produced
newFd AT_FDCWD bar @NUM@
done
Operation async_12 do
delFd @NUM@
done
Operation async_14 do
delFd @NUM@
done
Operation sync_14 do
hpath AT_FDCWD foo expunged
done
Operation sync_15 do
hpath AT_FDCWD bar expunged
done
Begin MAIN
@PROLOGUE_BLOCK@
submitOp sync_12 open SYNC
submitOp sync_13 close SYNC
newEvent 4 EXTERNAL
link 1 4
submitOp async_4 open ASYNC
newEvent 5 EXTERNAL
link 1 5
submitOp async_5 open ASYNC
newEvent 6 S 0
End
Begin 6
End
Begin 4
newEvent 7 EXTERNAL
link 4 7
End
Begin 5
End
Begin 7
newEvent 8 EXTERNAL
link 7 8
newEvent 9 S 0
End
Begin 9
newEvent 10 EXTERNAL
link 9 10
End
Begin 8
End
Begin 10
newEvent 11 S 0
End
Begin 11
newEvent 12 EXTERNAL
link 11 12
submitOp async_12 close ASYNC
newEvent 13 S 0
End
Begin 13
newEvent 14 EXTERNAL
link 13 14
submitOp async_14 close ASYNC
End
Begin 12
newEvent 15 S 0
End
Begin 15
End
Begin 14
newEvent 16 S 0
submitOp sync_14 unlink SYNC
submitOp sync_15 unlink SYNC
End
Begin 16
End
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping analysis output to STDOUT
1,4,creates
1,5,creates
1,6,creates
4,7,creates
6,4,before
6,5,before
7,8,creates
7,9,creates
9,8,before
9,10,creates
10,11,creates
11,12,creates
11,13,creates
12,15,creates
13,12,before
13,14,creates
14,16,creates
15,14,before
