@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD foo produced !open
newFd AT_FDCWD foo @NUM@ !open
done
Operation sync_13 do
delFd @NUM@ !close
done
Operation async_4 do
hpath AT_FDCWD foo consumed !open
newFd AT_FDCWD foo @NUM@ !open
done
Operation async_5 do
hpath AT_FDCWD bar produced !open
newFd AT_FDCWD bar @NUM@ !open
done
Operation async_12 do
delFd @NUM@ !close
done
Operation async_14 do
delFd @NUM@ !close
done
Operation sync_14 do
hpath AT_FDCWD foo expunged !unlink
done
Operation sync_15 do
hpath AT_FDCWD bar expunged !unlink
done
Begin MAIN
@PROLOGUE_BLOCK@
submitOp sync_12 SYNC !node_open
submitOp sync_13 SYNC !node_close
newEvent 4 EXTERNAL !fs !node_open
link 1 4
submitOp async_4 4 ASYNC !node_open
newEvent 5 EXTERNAL !fs !node_open
link 1 5
submitOp async_5 5 ASYNC !node_open
newEvent 6 S 0 !nextTick
End
Begin 6
End
Begin 4
newEvent 7 EXTERNAL
link 4 7
End
Begin 5
End
Begin 7
newEvent 8 EXTERNAL
link 7 8
newEvent 9 S 0 !nextTick
End
Begin 9
newEvent 10 EXTERNAL
link 9 10
End
Begin 8
End
Begin 10
newEvent 11 S 0 !nextTick
End
Begin 11
newEvent 12 EXTERNAL !fs !node_close
link 11 12
submitOp async_12 12 ASYNC !node_close
newEvent 13 S 0 !nextTick
End
Begin 13
newEvent 14 EXTERNAL !fs !node_close
link 13 14
submitOp async_14 14 ASYNC !node_close
End
Begin 12
newEvent 15 S 0 !nextTick
End
Begin 15
End
Begin 14
newEvent 16 S 0 !nextTick
submitOp sync_14 SYNC !node_unlink
submitOp sync_15 SYNC !node_unlink
End
Begin 16
End
@IGNORE@
1,4,creates
1,5,creates
1,6,creates
4,7,creates
6,4,before
6,5,before
7,8,creates
7,9,creates
9,8,before
9,10,creates
10,11,creates
11,12,creates
11,13,creates
12,15,creates
13,12,before
13,14,creates
14,16,creates
15,14,before
@IGNORE@
@CURRENT_DIR@/bar,5,produced
@CURRENT_DIR@/bar,14,expunged
@CURRENT_DIR@/foo,1,produced
@CURRENT_DIR@/foo,4,consumed
@CURRENT_DIR@/foo,14,expunged
@CURRENT_DIR@/stream.js,1,consumed
@IGNORE@
Number of data races: 1
* Event: 5 (tags: !fs !node_open) and Event: 14 (tags: !fs !node_close):
  - Path @CURRENT_DIR@/bar:
    produced by the first event (operation: open)
    expunged by the second event (operation: unlink)
