Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 S 0
End
Begin 4
newEvent 6 S 0
End
Begin 6
newEvent 7 S 0
End
Begin 7
newEvent 5 S 0
newEvent 8 S 0
End
DumpAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping dependency graph...
1,2
1,3
1,4
4,2
4,3
4,6
5,2
5,3
5,8
6,2
6,3
6,7
7,2
7,3
7,5
7,8
8,2
8,3
