@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD tmp produced
newFd AT_FDCWD tmp @NUM@
done
Operation sync_13 do
delFd @NUM@
done
Operation async_7 do
hpath AT_FDCWD tmp expunged
done
Operation async_8 do
hpath AT_FDCWD tmp consumed
done
Begin MAIN
@PROLOGUE_BLOCK@
submitOp sync_12 SYNC !open
submitOp sync_13 SYNC !close
newEvent 4 W 3 !setImmediate
newEvent 5 W 1 !setTimeout
newEvent 6 W 0 !timerWrap
End
Begin 6
trigger 5
newEvent 7 EXTERNAL !fs !unlink
link 5 7
submitOp async_7 7 ASYNC !unlink
End
Begin 7
End
Begin 4
newEvent 8 EXTERNAL !fs !access
link 4 8
submitOp async_8 8 ASYNC !access
End
Begin 8
End
@IGNORE@
1,4,creates
1,6,creates
4,7,before
4,8,creates
6,7,creates
@IGNORE@
@CURRENT_DIR@/timers.js,1,consumed
@CURRENT_DIR@/tmp,1,produced
@CURRENT_DIR@/tmp,7,expunged
@CURRENT_DIR@/tmp,8,consumed
