Starting the FSRacer Client...
NodeTrace: PID @NUM@, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation async_8 do
hpath AT_FDCWD foo consumed
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 W 1
newEvent 5 W 0
End
Begin 5
Link 5 4
newEvent 6 W 1
End
Begin 5
Link 5 6
newEvent 7 W 1
End
Begin 5
Link 5 7
newEvent 8 W 2
Link 7 8
SubmitOp async_8 access ASYNC
End
DumpAnalyzer: Analysis is done
