@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_10 do
hpath AT_FDCWD foo consumed
done
Begin MAIN
newEvent 2 EXTERNAL
link 1 2
newEvent 3 EXTERNAL
link 1 3
submitOp sync_1 stat SYNC
submitOp sync_2 lstat SYNC
submitOp sync_3 lstat SYNC
submitOp sync_4 lstat SYNC
submitOp sync_5 lstat SYNC
submitOp sync_6 lstat SYNC
submitOp sync_7 lstat SYNC
submitOp sync_8 lstat SYNC
submitOp sync_9 lstat SYNC
submitOp sync_10 open SYNC
submitOp sync_11 close SYNC
newEvent 4 W 1
newEvent 5 W 0
End
Begin 5
trigger 4
newEvent 6 W 1
newEvent 7 W 0
End
Begin 7
trigger 6
newEvent 8 W 1
newEvent 9 W 0
End
Begin 9
trigger 8
newEvent 10 EXTERNAL
link 8 10
submitOp async_10 access ASYNC
End
Begin 10
End
DependencyInferenceAnalyzer: Start analyzing traces...
DependencyInferenceAnalyzer: Analysis is done
DependencyInferenceAnalyzer: Dumping analysis output to STDOUT
1,5,creates
5,7,creates
7,9,creates
9,10,creates
