@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_10 do
hpath AT_FDCWD foo consumed
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 W 1 !setTimeout
newEvent 5 W 0 !timerWrap
End
Begin 5
trigger 4
newEvent 6 W 1 !setTimeout
newEvent 7 W 0 !timerWrap
End
Begin 7
trigger 6
newEvent 8 W 1 !setTimeout
newEvent 9 W 0 !timerWrap
End
Begin 9
trigger 8
newEvent 10 EXTERNAL !fs !access
link 8 10
submitOp async_10 10 ASYNC !access
End
Begin 10
End
@IGNORE@
1,5,creates
5,7,creates
7,9,creates
9,10,creates
@IGNORE@
@CURRENT_DIR@/foo,10,consumed
@CURRENT_DIR@/timers-nested2.js,1,consumed
