Starting the FSRacer Client...
NodeTrace: PID [0-9]+, Start collecting trace...
NodeTrace: Trace collected
DumpAnalyzer: Start analyzing traces...
@PROLOGUE_OPERATIONS@
Operation sync_12 do
hpath AT_FDCWD tmp produced
newFd tmp 19
done
Operation sync_13 do
delFd 19
done
Operation async_7 do
hpath AT_FDCWD tmp expunged
done
Operation async_8 do
hpath AT_FDCWD tmp consumed
done
Begin 1
@PROLOGUE_BLOCK@
SubmitOp sync_12 open SYNC
SubmitOp sync_13 close SYNC
newEvent 4 W 3
newEvent 5 W 1
newEvent 6 W 0
End
Begin 6
Link 6 5
newEvent 7 W 2
Link 5 7
SubmitOp async_7 unlink ASYNC
End
Begin 7
End
Begin 4
newEvent 8 W 2
Link 4 8
SubmitOp async_8 access ASYNC
End
Begin 8
End
DumpAnalyzer: Analysis is done
