@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_9 do
hpath AT_FDCWD bar consumed !access
done
Operation async_12 do
hpath AT_FDCWD foo consumed !access
done
Operation async_13 do
hpath AT_FDCWD baz consumed !access
done
Begin MAIN 1
@PROLOGUE_BLOCK@
newEvent 4 W 1 !setTimeout
newEvent 5 W 0 !timerWrap
newEvent 6 W 1 !setTimeout
newEvent 7 W 0 !timerWrap
newEvent 8 W 1 !setTimeout
End
Begin 5
trigger 4
newEvent 9 EXTERNAL !fs !node_access
link 4 9
submitOp async_9 9 ASYNC !node_access
newEvent 10 W 1 !setTimeout
newEvent 11 W 0 !timerWrap
trigger 8
newEvent 12 EXTERNAL !fs !node_access
link 8 12
submitOp async_12 12 ASYNC !node_access
End
Begin 7
trigger 6
newEvent 13 EXTERNAL !fs !node_access
link 6 13
submitOp async_13 13 ASYNC !node_access
End
Begin 11
trigger 10
End
Begin 9
End
Begin 12
End
Begin 13
End
@IGNORE@
5,11,creates
5,12,creates
5,7,before
5,9,creates
7,11,before
7,13,creates
MAIN_1,5,creates
MAIN_1,7,creates
@IGNORE@
@CURRENT_DIR@/bar,9,consumed
@CURRENT_DIR@/baz,13,consumed
@CURRENT_DIR@/foo,12,consumed
@CURRENT_DIR@/timers-different-timeout.js,MAIN_1,consumed
@IGNORE@
