@PREAMBLE@
@PROLOGUE_OPERATIONS@
Operation async_8 do
hpath AT_FDCWD foo consumed !access
done
Begin MAIN
@PROLOGUE_BLOCK@
newEvent 4 W 1 !setTimeout
newEvent 5 W 0 !timerWrap
End
Begin 5
trigger 4
newEvent 6 W 1 !setTimeout
End
Begin 5
trigger 6
newEvent 7 W 1 !setTimeout
End
Begin 5
trigger 7
newEvent 8 EXTERNAL !fs !node_access
link 7 8
submitOp async_8 8 ASYNC !node_access
End
@IGNORE@
1,5,creates
@IGNORE@
@CURRENT_DIR@/foo,8,consumed
@CURRENT_DIR@/timers-nested-err.js,1,consumed
