#!/bin/bash

NAME_T="$(cat $1 | grep 'Source: ' | cut -d ':' -f2)"
NAME="$(echo -e "${NAME_T}" | tr -d '[:space:]')"

cd $2

mkdir -p /results/$NAME

echo "$(pwd)" > /results/$NAME/$NAME.path

# A more random approach, we can't build project depending on cmake and more.
debian/rules clean 2> /results/$NAME/$NAME.conferr
debian/rules build
if [ -f Makefile ]; then
  make clean
  strace -s 300 -f -e "$(tr -s '\r\n' ',' < /build/syscalls.txt | \
    sed -e 's/,$/\n/')" -o /results/$NAME/$NAME.strace fsmake-make 2> /results/$NAME/$NAME.strerr
  make -pn > /results/$NAME/$NAME.makedb
else
  rm -rf /results/$NAME/*
  echo "Couln't find Makefile" > /results/$NAME/$NAME.warning
fi

